#!/bin/bash
# shellcheck disable=SC2016

# ==========================================================================
# BGG Geeklist Math Trade Importer
# Generated by Antigravity AI
# ==========================================================================

# --- CONFIGURATION ---
GEEKLIST_ID="379213"
# Choose authentication method (uncomment and populate the one you prefer):
# Method A: Cookie-based (for legacy form POST)
GEEK_SESSION=""

# Method B: Bearer Token (for modern API JSON POST)
BEARER_TOKEN=""

# Verification check
if [ -z "$GEEK_SESSION" ] && [ -z "$BEARER_TOKEN" ]; then
  echo "Error: You must set either GEEK_SESSION cookie or BEARER_TOKEN in the script configuration!"
  exit 1
fi

# --- HELPER FUNCTION ---
add_item() {
  local title="$1"
  local bgg_id="$2"
  local comment="$3"
  local json_payload="$4"

  echo "Adding: $title (BGG ID: $bgg_id)..."
  local response
  if [ -n "$BEARER_TOKEN" ]; then
    # Modern API JSON POST (Bearer Token)
    response=$(curl -w "\nHTTP_STATUS:%{http_code}" -s -X POST "https://api.geekdo.com/api/geeklist/$GEEKLIST_ID/listitem" \
      -H "Content-Type: application/json" \
      -H "Authorization: Bearer $BEARER_TOKEN" \
      -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36" \
      -H "Accept: application/json, text/plain, *\/*" \
      -H "Origin: https://boardgamegeek.com" \
      -H "Referer: https://boardgamegeek.com/" \
      -d "$json_payload")
  elif [ -n "$GEEK_SESSION" ]; then
    # Modern API JSON POST (GeekSession Cookie value as GeekAuth)
    response=$(curl -w "\nHTTP_STATUS:%{http_code}" -s -X POST "https://api.geekdo.com/api/geeklist/$GEEKLIST_ID/listitem" \
      -H "Content-Type: application/json" \
      -H "Authorization: GeekAuth $GEEK_SESSION" \
      -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36" \
      -H "Accept: application/json, text/plain, *\/*" \
      -H "Origin: https://boardgamegeek.com" \
      -H "Referer: https://boardgamegeek.com/" \
      -d "$json_payload")
  else
    echo "Error: Neither BEARER_TOKEN nor GEEK_SESSION is set!"
    exit 1
  fi
  echo "Response from server:"
  echo "$response"
  echo "  Done. Waiting 5 seconds to comply with BGG rate limits..."
  sleep 5
}

echo "Starting import of games to BGG Geeklist $GEEKLIST_ID..."


# Game: Santorini
# add_item 'Santorini' '194655' 'Excellent condition
# First edition
# Contains the Golden Fleece expansion
# (non-smoking household)
# 
# Fun game! (It just doesn'\''t get to the table.)
# 
# Will cover the first $10 outside of CONUS' '{"item": {"type": "thing", "id": "194655"}, "imageid": null, "imageOverridden": false, "body": "Excellent condition\nFirst edition\nContains the Golden Fleece expansion\n(non-smoking household)\n\nFun game! (It just doesn'\''t get to the table.)\n\nWill cover the first $10 outside of CONUS", "rollsEnabled": false}'
# 
# # Game: Pandemic
# add_item 'Pandemic' '30549' 'New in Shrink
# 2013 version
# (non-smoking household)
# 
# Will cover the first $10 outside of CONUS' '{"item": {"type": "thing", "id": "30549"}, "imageid": null, "imageOverridden": false, "body": "New in Shrink\n2013 version\n(non-smoking household)\n\nWill cover the first $10 outside of CONUS", "rollsEnabled": false}'

# Game: 5-Minute Marvel
add_item '5-Minute Marvel' '253618' 'Like new
Played twice
(non-smoking household)

Will cover the first $10 outside of CONUS' '{"item": {"type": "thing", "id": "253618"}, "imageid": null, "imageOverridden": false, "body": "Like new\nPlayed twice\n(non-smoking household)\n\nWill cover the first $10 outside of CONUS", "rollsEnabled": false}'

# Game: Pandemic: Hot Zone – North America
add_item 'Pandemic: Hot Zone – North America' '301919' 'New in Shrink
(non-smoking household)

Will cover the first $10 outside of CONUS' '{"item": {"type": "thing", "id": "301919"}, "imageid": null, "imageOverridden": false, "body": "New in Shrink\n(non-smoking household)\n\nWill cover the first $10 outside of CONUS", "rollsEnabled": false}'

# Game: Moongha Invaders: Mad Scientists and Atomic Monsters Attack the Earth!
add_item 'Moongha Invaders: Mad Scientists and Atomic Monsters Attack the Earth!' '64826' 'New in Shrink
(non-smoking household)

Will cover first $10 outside of CONUS' '{"item": {"type": "thing", "id": "64826"}, "imageid": null, "imageOverridden": false, "body": "New in Shrink\n(non-smoking household)\n\nWill cover first $10 outside of CONUS", "rollsEnabled": false}'

# Game: Castles of Mad King Ludwig
add_item 'Castles of Mad King Ludwig' '155426' 'Excellent condition

Great game, but nobody else in my house will play it
(non-smoking household)

Will cover first $10 outside of CONUS' '{"item": {"type": "thing", "id": "155426"}, "imageid": null, "imageOverridden": false, "body": "Excellent condition\n\nGreat game, but nobody else in my house will play it\n(non-smoking household)\n\nWill cover first $10 outside of CONUS", "rollsEnabled": false}'

# Game: Infinity Gauntlet: A Love Letter Game
add_item 'Infinity Gauntlet: A Love Letter Game' '304285' 'Like new!
Comes in the standard purple Marvel Infinity Gauntlet bag

(non-smoking household)

Will cover first $10 outside of CONUS' '{"item": {"type": "thing", "id": "304285"}, "imageid": null, "imageOverridden": false, "body": "Like new!\nComes in the standard purple Marvel Infinity Gauntlet bag\n\n(non-smoking household)\n\nWill cover first $10 outside of CONUS", "rollsEnabled": false}'

# Game: Rumble in the House
add_item 'Rumble in the House' '99437' 'New in Shrink
(non-smoking household)

Will cover first $10 outside of CONUS' '{"item": {"type": "thing", "id": "99437"}, "imageid": null, "imageOverridden": false, "body": "New in Shrink\n(non-smoking household)\n\nWill cover first $10 outside of CONUS", "rollsEnabled": false}'

# Game: Monopoly: The Card Game
add_item 'Monopoly: The Card Game' '684' 'Cards in Shrink
(non-smoking household)

Will cover the first $10 outside of CONUS' '{"item": {"type": "thing", "id": "684"}, "imageid": null, "imageOverridden": false, "body": "Cards in Shrink\n(non-smoking household)\n\nWill cover the first $10 outside of CONUS", "rollsEnabled": false}'

# Game: Boss Monster: The Dungeon Building Card Game
add_item 'Boss Monster: The Dungeon Building Card Game' '131835' 'Great condition, very minor shelf corner wear, game was played a couple of times.

Great game, not getting played though.
(non-smoking household)

Will cover first $10 outside of CONUS' '{"item": {"type": "thing", "id": "131835"}, "imageid": null, "imageOverridden": false, "body": "Great condition, very minor shelf corner wear, game was played a couple of times.\n\nGreat game, not getting played though.\n(non-smoking household)\n\nWill cover first $10 outside of CONUS", "rollsEnabled": false}'

# Game: BattleCON: War of Indines (2012)
add_item 'BattleCON: War of Indines (2012)' '89409' 'New in Shrink
(non-smoking household)

Will cover the first $10 outside of CONUS' '{"item": {"type": "thing", "id": "89409"}, "imageid": null, "imageOverridden": false, "body": "New in Shrink\n(non-smoking household)\n\nWill cover the first $10 outside of CONUS", "rollsEnabled": false}'

echo "All games processed."
