import re
import os
import json

def parse_games(md_path):
    if not os.path.exists(md_path):
        print(f"Error: {md_path} not found.")
        return []

    with open(md_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Split by sections starting with ## (at the beginning of a line)
    sections = re.split(r'^##\s+', content, flags=re.MULTILINE)
    
    games = []
    # Skip sections[0] as it contains the main title `# Games for trade`
    for section in sections[1:]:
        lines = section.split('\n')
        if not lines:
            continue
        
        title = lines[0].strip()
        
        # Extract BGG ID and Link
        bgg_id = None
        bgg_link = None
        for line in lines:
            match = re.search(r'https://boardgamegeek\.com/boardgame[a-z]*/(\d+)', line)
            if match:
                bgg_id = match.group(1)
                bgg_link = line.strip().replace('- BGG Link: ', '')
                break
        
        if not bgg_id:
            # Fallback for simpler links
            for line in lines:
                match = re.search(r'boardgamegeek\.com/boardgame/(\d+)', line)
                if match:
                    bgg_id = match.group(1)
                    break
        
        # Extract description / comments
        description_lines = []
        in_desc = False
        for line in lines:
            if line.strip().startswith('### Description'):
                in_desc = True
                continue
            if in_desc:
                description_lines.append(line)
        
        description = '\n'.join(description_lines).strip()
        
        if bgg_id:
            games.append({
                'title': title,
                'id': bgg_id,
                'link': bgg_link,
                'description': description
            })
        else:
            print(f"Warning: Could not find BGG ID for game '{title}'")
            
    return games

def extract_existing_config(output_path="add_games.sh"):
    geek_session = ""
    bearer_token = ""
    if os.path.exists(output_path):
        with open(output_path, 'r', encoding='utf-8') as f:
            content = f.read()
        session_match = re.search(r'GEEK_SESSION="([^"]*)"', content)
        token_match = re.search(r'BEARER_TOKEN="([^"]*)"', content)
        if session_match:
            geek_session = session_match.group(1)
        if token_match:
            bearer_token = token_match.group(1)
    return geek_session, bearer_token

def generate_bash_script(games, geeklist_id="379213", output_path="add_games.sh"):
    # Extract currently set session/token from the existing script to preserve user changes
    existing_session, existing_token = extract_existing_config(output_path)
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("#!/bin/bash\n")
        f.write("# shellcheck disable=SC2016\n\n")
        f.write("# ==========================================================================\n")
        f.write("# BGG Geeklist Math Trade Importer\n")
        f.write("# Generated by Antigravity AI\n")
        f.write("# ==========================================================================\n\n")
        
        f.write("# --- CONFIGURATION ---\n")
        f.write(f"GEEKLIST_ID=\"{geeklist_id}\"\n")
        f.write("# Choose authentication method (uncomment and populate the one you prefer):\n")
        f.write("# Method A: Cookie-based (for legacy form POST)\n")
        f.write(f"GEEK_SESSION=\"{existing_session}\"\n\n")
        f.write("# Method B: Bearer Token (for modern API JSON POST)\n")
        f.write(f"BEARER_TOKEN=\"{existing_token}\"\n\n")
        
        f.write("# Verification check\n")
        f.write("if [ -z \"$GEEK_SESSION\" ] && [ -z \"$BEARER_TOKEN\" ]; then\n")
        f.write("  echo \"Error: You must set either GEEK_SESSION cookie or BEARER_TOKEN in the script configuration!\"\n")
        f.write("  exit 1\n")
        f.write("fi\n\n")
        
        # Define the DRY helper function in the shell script
        f.write("# --- HELPER FUNCTION ---\n")
        f.write("add_item() {\n")
        f.write("  local title=\"$1\"\n")
        f.write("  local bgg_id=\"$2\"\n")
        f.write("  local comment=\"$3\"\n")
        f.write("  local json_payload=\"$4\"\n\n")
        f.write("  echo \"Adding: $title (BGG ID: $bgg_id)...\"\n")
        f.write("  local response\n")
        f.write("  if [ -n \"$BEARER_TOKEN\" ]; then\n")
        f.write("    # Modern API JSON POST (Bearer Token)\n")
        f.write("    response=$(curl -w \"\\nHTTP_STATUS:%{http_code}\" -s -X POST \"https://api.geekdo.com/api/geeklist/$GEEKLIST_ID/listitem\" \\\n")
        f.write("      -H \"Content-Type: application/json\" \\\n")
        f.write("      -H \"Authorization: Bearer $BEARER_TOKEN\" \\\n")
        f.write("      -H \"User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36\" \\\n")
        f.write("      -H \"Accept: application/json, text/plain, *\\/*\" \\\n")
        f.write("      -H \"Origin: https://boardgamegeek.com\" \\\n")
        f.write("      -H \"Referer: https://boardgamegeek.com/\" \\\n")
        f.write("      -d \"$json_payload\")\n")
        f.write("  elif [ -n \"$GEEK_SESSION\" ]; then\n")
        f.write("    # Modern API JSON POST (GeekSession Cookie value as GeekAuth)\n")
        f.write("    response=$(curl -w \"\\nHTTP_STATUS:%{http_code}\" -s -X POST \"https://api.geekdo.com/api/geeklist/$GEEKLIST_ID/listitem\" \\\n")
        f.write("      -H \"Content-Type: application/json\" \\\n")
        f.write("      -H \"Authorization: GeekAuth $GEEK_SESSION\" \\\n")
        f.write("      -H \"User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36\" \\\n")
        f.write("      -H \"Accept: application/json, text/plain, *\\/*\" \\\n")
        f.write("      -H \"Origin: https://boardgamegeek.com\" \\\n")
        f.write("      -H \"Referer: https://boardgamegeek.com/\" \\\n")
        f.write("      -d \"$json_payload\")\n")
        f.write("  else\n")
        f.write("    echo \"Error: Neither BEARER_TOKEN nor GEEK_SESSION is set!\"\n")
        f.write("    exit 1\n")
        f.write("  fi\n")
        f.write("  echo \"Response from server:\"\n")
        f.write("  echo \"$response\"\n")
        f.write("  echo \"  Done. Waiting 5 seconds to comply with BGG rate limits...\"\n")
        f.write("  sleep 5\n")
        f.write("}\n\n")
        
        f.write("echo \"Starting import of games to BGG Geeklist $GEEKLIST_ID...\"\n\n")
        
        for game in games:
            title = game['title']
            bgg_id = game['id']
            description = game['description']
            
            # Escape single quotes for bash single-quoted arguments
            escaped_title = title.replace("'", "'\\''")
            escaped_desc = description.replace("'", "'\\''")
            
            # Generate JSON payload according to api.geekdo.com schema
            payload = {
                "item": {
                    "type": "thing",
                    "id": bgg_id
                },
                "imageid": None,
                "imageOverridden": False,
                "body": description,
                "rollsEnabled": False
            }
            json_payload = json.dumps(payload, ensure_ascii=False)
            escaped_json_payload = json_payload.replace("'", "'\\''")
            
            f.write(f"\n# Game: {title}\n")
            f.write(f"add_item '{escaped_title}' '{bgg_id}' '{escaped_desc}' '{escaped_json_payload}'\n")
            
        f.write("\necho \"All games processed.\"\n")
        
    print(f"Generated {output_path} successfully with {len(games)} games.")

if __name__ == "__main__":
    games = parse_games("games.md")
    generate_bash_script(games)
